apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-ca-cert-config
  namespace: rocmqa
data:
  registry-sc-harbor.amd.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFJDCCBAygAwIBAgITXwAG/usN8NE90E39GgABAAb+6zANBgkqhkiG9w0BAQsF
    ADBHMRMwEQYKCZImiZPyLGQBGRYDY29tMRMwEQYKCZImiZPyLGQBGRYDYW1kMRsw
    GQYDVQQDExJBTUQtY29tIElzc3VpbmcgQ0EwHhcNMjUwNDE4MDUzNTM3WhcNMjYw
    NDE4MDUzNTM3WjCBrTELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRQwEgYDVQQH
    EwtTYW50YSBDbGFyYTEfMB0GA1UEChMWQWR2YW5jZWQgTWljcm8gRGV2aWNlczEO
    MAwGA1UECxMFRU5HSVQxIzAhBgNVBAMTGnJlZ2lzdHJ5LXNjLWhhcmJvci5hbWQu
    Y29tMSUwIwYJKoZIhvcNAQkBFhZkbC5NTFNFLkRldk9wc0BhbWQuY29tMIIBIjAN
    BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp/46qmpCovBdVPy1nXFl/QC0WkT7
    Wg00fZwErwjnI1yIbgNu5W8e+ImuYC5unkFQL9qDrqg3rkVpWO9AQenTyE9Kav13
    zdVZ4ssdRkjy5CcCtMaY5IVEqtumxTg73r19GlOj7rnWexeam/3c9zPduALQOsZ/
    hvsMxWrRBhq8O2R62FRLxpks54KrQpl8qAuYahP2Mgv+DJW0gf5ubqhNHv4BqOfT
    26uneZPOkEeod51l4P1rbrBNPrjTL20/uISawwwcqhvDGm5U6YNrk7MVPGRuauZM
    RKxHYbkOqXubVOozFbaQo4Jwp5qOAixoYu3cRIr4A44vqUxhpAFRsES89QIDAQAB
    o4IBoDCCAZwwJQYDVR0RBB4wHIIacmVnaXN0cnktc2MtaGFyYm9yLmFtZC5jb20w
    HQYDVR0OBBYEFKF4fV1jk+q7s4u9Z229ObOr0yGJMB8GA1UdIwQYMBaAFP0k8PRa
    NYdNGe+MjPVn8DFXZ698MEkGA1UdHwRCMEAwPqA8oDqGOGh0dHA6Ly9wa2kuYW1k
    LmNvbS9DZXJ0RW5yb2xsL0FNRC1jb20lMjBJc3N1aW5nJTIwQ0EuY3JsMGoGCCsG
    AQUFBwEBBF4wXDBaBggrBgEFBQcwAoZOaHR0cDovL3BraS5hbWQuY29tL0NlcnRF
    bnJvbGwvQXRsY2VydHAwMS5hbWQuY29tX0FNRC1jb20lMjBJc3N1aW5nJTIwQ0Eo
    MSkuY3J0MAsGA1UdDwQEAwIFoDA9BgkrBgEEAYI3FQcEMDAuBiYrBgEEAYI3FQiH
    vadJhJXyJ4XFgxuC8adgg6ChLB+BkP0ph6CVagIBZAIBQTATBgNVHSUEDDAKBggr
    BgEFBQcDATAbBgkrBgEEAYI3FQoEDjAMMAoGCCsGAQUFBwMBMA0GCSqGSIb3DQEB
    CwUAA4IBAQAOs5Gjwv+3JAupzSVE4/wTua0WWBm6txhR0fCz7qX50EsSSRk9WRhd
    YilQ/GOssoSdvBgMa3/orgdw5T6A09wXF+rpcEayeZclaZw+7m+k0Rx+F2afbwPW
    s+isxAa3q9YiyTgVzOQ+x9DFE8axDBzqSxAV9S7vQiB/90YDnuz/v29isRDuPNvu
    WbGGVLs4evdNBe/qDljV1D1u7eqb0ycngALF+PHS7DjtgybvQXNiJIt/w9t0YGNn
    uG+EcBExRwxWjRFB6/oFBvTKjaVogjJeCvOEmILxX1p3Nqz2tcalm/L5ap0AtQw9
    N0meHFg6kRkOoQ835dvpeL+sHsUcppq7
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIGBjCCA+6gAwIBAgITZAAAAAfoLGwCLB/mTwABAAAABzANBgkqhkiG9w0BAQsF
    ADAgMR4wHAYDVQQDExVBTUQgQ29ycG9yYXRlIFJvb3QgQ0EwHhcNMjIwODA2MTYz
    MTM4WhcNMzIwODA2MTMyNDM3WjBHMRMwEQYKCZImiZPyLGQBGRYDY29tMRMwEQYK
    CZImiZPyLGQBGRYDYW1kMRswGQYDVQQDExJBTUQtY29tIElzc3VpbmcgQ0EwggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCXhWxJ40hfmob0hyWQ9/aUb8X3
    EnwVKLiMlQDWS9kiuw4xwpufhMWZDDLSwy+Q1fQYGAmLx73vwkFAyRElq7TgcxDO
    Wu3GkwO3tLHYNs1JQPgwzImMbgBc/5WECsBQC6VtGGF7V3bLHnkpb4oJmxDg6wo8
    ZZIFbGTcKKUH4vNfDUZojKUL++PUHLFk6vVqp/jObU+dl1yBYiqdQHef2bRKhcVn
    f7f/mROvt6DQh4Aa8q8QaEww/aRYT2SvO0V25sW8rpn4/fVBx0Q1C06Z3sIV443M
    +uW8QSSw80AYxGzNskbQjiHZeBV4jQUVzziQPUVi5dAITIrd9VTIfY5pp6W3AgMB
    AAGjggIQMIICDDAQBgkrBgEEAYI3FQEEAwIBATAjBgkrBgEEAYI3FQIEFgQUCP0a
    csSp99QVB0SPGUSqpZT9EwcwHQYDVR0OBBYEFP0k8PRaNYdNGe+MjPVn8DFXZ698
    MBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIAQwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMB
    Af8EBTADAQH/MB8GA1UdIwQYMBaAFJePJcoXAtjA+rr/OpVBZPPFByrjMIGUBgNV
    HR8EgYwwgYkwgYaggYOggYCGPWh0dHA6Ly9wa2kuYW1kLmNvbS9DZXJ0RW5yb2xs
    L0FNRCUyMENvcnBvcmF0ZSUyMFJvb3QlMjBDQS5jcmyGP2h0dHA6Ly9wa2kuZG16
    LmxvY2FsL0NlcnRFbnJvbGwvQU1EJTIwQ29ycG9yYXRlJTIwUm9vdCUyMENBLmNy
    bDCBwgYIKwYBBQUHAQEEgbUwgbIwVgYIKwYBBQUHMAKGSmh0dHA6Ly9wa2kuYW1k
    LmNvbS9DZXJ0RW5yb2xsL0F0bGNlcnRwcl9BTUQlMjBDb3Jwb3JhdGUlMjBSb290
    JTIwQ0EoMSkuY3J0MFgGCCsGAQUFBzAChkxodHRwOi8vcGtpLmRtei5sb2NhbC9D
    ZXJ0RW5yb2xsL0F0bGNlcnRwcl9BTUQlMjBDb3Jwb3JhdGUlMjBSb290JTIwQ0Eo
    MSkuY3J0MA0GCSqGSIb3DQEBCwUAA4ICAQB6A6bXDGE6zXJDndTCgsEEOyN8V8UO
    mBljJKmB7Dk9GxjtfbAzm9zz6AdTlqns2ZD7KRQcJGPFNvot1Kqu+LkX+RzoXMq6
    rs3YvfvbEzml+JJYoI/fkUyF8z9T5i60GIi2uMRuZdn7lh2b0AipzSDx3DSHpTfV
    0kX/7X9CD6TpGikZdjUmawRD8pEiA2GXCiPVxmfKkuzYaNy+vYuQPxT1pZ3cLr1Q
    XT+pip0MJU4HC9AflUKrBws2YSEaCY11fe0d3zXJQ/sZ7DPlVp5xraCbsb9k0+2h
    o697CMwqrV81aVVan4YiCJ0zQHZc0Ye0M24QfmgpxQSxu8LipgO2SzJaqaakbWfB
    bibMHuWBcnw5VKeck7vkQjUrH3eKqNWt88XM6nu6qGkiMFJyzIBfqjPGmS8+gAR2
    Jeo1pcsyDkuFdwj9k67iQeSjANTVzhIBvgbWheTskSEsoL/aEdHnkRrKBX4Rvbnj
    xUCguoTdYj/u3oGHp3bqtWMFWmKDSQIEvX1iFdJxOEK+KD+eIxXzFplEjvmPa9Il
    uuN978qJbMAC8L17Zsumbmxcvp2KhxPlrtXlSiWN/yA0GmwyCJVqAayMAxytJ1GF
    1828gYbvFwxWSPYH0Gow1E27m47SayYSflYvz7PN6KC1aYyupwmlM3Hiwo1cuqXa
    hbGw6my8ll3Pog==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFQDCCAyigAwIBAgIQT+Cof5rlpZ5D6UTomkDR8zANBgkqhkiG9w0BAQsFADAg
    MR4wHAYDVQQDExVBTUQgQ29ycG9yYXRlIFJvb3QgQ0EwHhcNMTQwNDA3MTgzNTI5
    WhcNMzIwODA2MTMyNDM3WjAgMR4wHAYDVQQDExVBTUQgQ29ycG9yYXRlIFJvb3Qg
    Q0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCaxvtiduTuBrMbq+3U
    /w8ma2wwcoVGtJq50ah2BA45dXetW0NcwuZPGxeNnsxYR1PLVkQDlO+gJP8XKgY7
    RmIaScaVnIeRImTzwljjOHw6kgf2+8QyU+/eXyIWb97Sl9BZCDys99WN2fam8FpO
    XBgT89WrZwdfFliUwNcEgtJf3mgEpk3BwUSHzmMvCNjdRpYTuHEDEC3yuIIIb0nW
    Bocun9dSID418FFqLjitQJtwhV5AHUQBvsJwAS7KosEGNSZ4jbBrDGmYSF1zMHav
    34UgiLbJx8D3hL3EaHht35j2NfbMoDxm+ysTlCYAJDW+DVpNzCojgReZK+mIzC7Q
    l3jrbh593JjFLdkDL+XSGxCGAG3whF4qpPh/nSF/eBvMBB6Ii0g2gQx0eXAwoLA6
    wfzu74OGvMm6CNMsDYCvHtGpnN/3DemDWhyNoDdeETebIWHNavqBxzsQKWdvzt2J
    jFWoPOocYY45v6yYoKpHSSv3CVd7BZQaoblazCCFk98Vy2gV/XJmPGe8je2wktsp
    qJ9MOXCT4e/H33UuNPN21aFEuvc4q4d0/OoJ+PAQodSHPqOzwYITAUxy9xg1+jDg
    kxV/UYL4CuJdshPxOkMOpts1tfeYNXXaTATd7dTINvB/8AQNd7TO1R9JKgBhxSsx
    klrDNU5IovMCHoK0ZvzYkk7OVQIDAQABo3YwdDALBgNVHQ8EBAMCAYYwDwYDVR0T
    AQH/BAUwAwEB/zAdBgNVHQ4EFgQUl48lyhcC2MD6uv86lUFk88UHKuMwEAYJKwYB
    BAGCNxUBBAMCAQEwIwYJKwYBBAGCNxUCBBYEFPLcQs794DL9kzJ9cpdrsKis+t+z
    MA0GCSqGSIb3DQEBCwUAA4ICAQBran/q1wT85v2psOgfb7hGI8YcsobL8K70fXur
    +rZqCn+g5n+d7LLNoU+A5bkPrVDXQ915nH8ZkGZX6iEt6OifpqHz8G05ok8Ab/0A
    ihTVHPaPlnuAjN7ZIDsDKO4eI5q8EqTZu21XxzaG0dczBsQfl8N08WjiQ/4yDQ4A
    QMIQ632C3ULc0j43jbWWK2JvG2HNzwRCp8vm8VKO5skyXa3LKa3xAyYMg8g0dMPM
    tb2o0zPsudTIOM4ftJTcvYjpA8uRBD2P9C+jTTGog1RDZ2q5608wIvLMwN4e0Gew
    y7/n+UQeF79LPBySc8uGboin/wDAS1/KIYAI+sIMdSgauAAns3cViC/ZLSYelHjG
    IGFK5rhKt7rgfOiy7+m/AZtGdJv6Y+gGQQ2ZG8hwk+y9rse7PAOWwYCpHHGqJ2MJ
    gxaUKXbJzOTaRLDSpqjBtfVUQm/0aWfSKwYxlPivV4BLB44o0N5B8F9AHopkt/Et
    fM+RJkhLyyx3qYBuhl32P28FBk+qYEmSS7rwmsin4Mnj6TfoeqqvrA8PJI0npp69
    mU93mZ3r2ITVxjvObUdlW9EK7tk6aUJpNSPmwEBQK3CXCk+osku1iYARrXZnAHXp
    4lFYj3O6xrCNX5nGydladcaQ4kEyScTdzQ7FGMx3++FCZUnELPT7AsgbWyd4uxJO
    Hqfi/A==
    -----END CERTIFICATE-----
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: harbor-artifactory-cert-installer
  namespace: rocmqa
spec:
  selector:
    matchLabels:
      name: harbor-artifactory-cert-installer
  template:
    metadata:
      labels:
        name: harbor-artifactory-cert-installer
    spec:
      nodeSelector:
        feature.node.kubernetes.io/amd-vgpu: "true"
   
      tolerations:
      - operator: Exists
      containers:
      - name: cert-installer
        image: registry-sc-harbor.amd.com/rocm-ci-images/compute-rocm-dkms-no-npi-hipclang:16302-ubuntu-22.04
        securityContext:
          privileged: true
        command: ["/bin/bash"]
        args:
        - -c
        - |
          if [ ! -f /usr/local/share/ca-certificates/registry-sc-harbor.amd.crt ]; then
            echo "Starting CA certificate update on node $(hostname)" && \
            cp /certs/registry-sc-harbor.amd.crt /usr/local/share/ca-certificates/ && \
            chroot /host update-ca-certificates && \
            echo "Certificate update completed on node: $(hostname)"
          else
            echo "Certificate already exists on node"
          fi
          while true; do  
            sleep 3600  
            echo "Certificate check running. Last check: $(date)" 
          done  

        volumeMounts:
        - name: host-root
          mountPath: /host
        - name: ca-certificates
          mountPath: /usr/local/share/ca-certificates
        - name: cert-volume
          mountPath: /certs
      imagePullSecrets:
      - name: ibm-cloud-k8
      volumes:
      - name: host-root
        hostPath:
          path: /
      - name: ca-certificates
        hostPath:
          path: /usr/local/share/ca-certificates
      - name: cert-volume
        configMap:
          name: harbor-ca-cert-config
      restartPolicy: Always

 
